### PR TITLE
Downgraded bundler

### PR DESCRIPTION
**Pull request by MichaelKuhinica**

### CODE REVIEW

**Comment by MichaelKuhinica** [comment]
Still failing. I will check it again.

**Comment by clod81** [comment]
```
Failures:
  1) Jemquarie::Importer with no date parameters should accept parameters with account number but no date parameters without error
     Failure/Error: expect(FakeWeb.last_request.body.include?("<tns:item1></tns:item1>")).to be_true
       expected true to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/lib/importer_spec.rb:171:in `block (3 levels) in <top (required)>'
```

**Comment by MichaelKuhinica** [comment]
Working on it.
How about those errors installing `rack`. Do you have any clue?

**Comment by clod81** [comment]
```
rack requires Ruby version >= 2.2.2.
```

not too sure to be honest. I'm not really involved with programming much lately.
If you want to become maintainer of the gem, feel free.

**Comment by MichaelKuhinica** [comment]
That would be great! My handler on RubyGems is MichaelKuhinica.

**Comment by clod81** [comment]
should be done

**Pull request merged**
